sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t avjsingh/docker-react .

script:
  - docker run -e CI=true avjsingh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-659885002145"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
